version: "2"
services:
  nginx:
    image: nginx:1.15.2
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./ingeleser_app:/app

  postgres:
    image: postgres:10.4
    env_file: .env

  app:
    image: ingeleser_web
    build: ./app
    volumes:
      - ./app:/app
    env_file: .env
    restart: on-failure
    command: sh ./scripts/dev.sh

  redis:
    image: redis:3.2.8
