version: "2"
services:
  nginx:
    extends:
      file: base.yml
      service: nginx
    links:
      - app
    ports:
      - "5000:5000"

  postgres:
    extends:
      file: base.yml
      service: postgres

  redis:
    extends:
      file: base.yml
      service: redis

  app:
    extends:
      file: base.yml
      service: app
    environment:
      - DJANGO_SETTINGS_MODULE=service.settings.dev_settings
    build:
      args:
        - DJANGO_ENV=dev
    links:
      - postgres
      - redis
    ports:
      - "8000:8000"