"""
Django settings for formatcom project.

Generated by 'django-admin startproject' using Django 2.0.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""
import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

PROJECT_NAME = 'service'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'SECRET_KEY'


ALLOWED_HOSTS = ['*']


# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'constance',
    'storages',
]

INSTALLED_APPS = [
    'app.service.app',
    'app.service.corporativeinfo',

] + INSTALLED_APPS


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

ROOT_URLCONF = '{0}.urls'.format(PROJECT_NAME)

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = '{0}.wsgi.application'.format(PROJECT_NAME)

# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME':     os.environ.get('POSTGRES_DB',       ''),
        'USER':     os.environ.get('POSTGRES_USER',     ''),
        'PASSWORD': os.environ.get('POSTGRES_PASSWORD', ''),
        'HOST':     'postgres',
        'PORT':     '5432',
    }
}

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

CONSTANCE_BACKEND = 'constance.backends.redisd.RedisBackend'
CONSTANCE_CONFIG = {
    'TEXTO_NOSOTROS': (
        """
            Somos una empresa dedicada al servicio profesional de ingeniería
            electromecánica, mantenimiento, instalaciones, fabricación,
            suministro y montaje de tableros electrónicos, brindando asesoria
            a nivel local y regional.
        """,
        'Texto de la sección "Nosotros"',
    ),
    'DIRECCION': (
        'Parque Agroindustrial de la Sabana, km 18 vía occidente, bodega 62',
        'Dirección',
    ),
    'CIUDAD': (
        'Mosquera - Cundimamarca',
        'Ciudad',
    ),
    'TELEFONO_1': (
        '(571) 659-3136',
        'Teléfono de contacto 1',
    ),
    'TELEFONO_2': (
        '(571) 827-9631',
        'Teléfono de contacto 2',
    ),
    'TELEFONO_CELULAR': (
        '+(57) 3112554413',
        'Teléfono celular de contacto',
    ),
    'CORREO': (
        'ingenelectro@outlook.com',
        'Correo electrónico de contacto',
    ),
}

CONSTANCE_CONFIG_FIELDSETS = {
    'Ubicación': ('DIRECCION', 'CIUDAD'),
    'Teléfonos de contacto': (
        'TELEFONO_1',
        'TELEFONO_2',
        'TELEFONO_CELULAR',
    ),
    'Correo de contacto': (
        'CORREO',
    ),
    'Secciones': (
        'TEXTO_NOSOTROS',
    )
}

LANGUAGE_CODE = 'es-co'
TIME_ZONE = 'America/Bogota'
USE_I18N = True
USE_L10N = True
USE_TZ = True

REDIS_HOST = 'redis'
REDIS_PORT = 6379

CONSTANCE_REDIS_PREFIX = 'constance: Ingeleser:'
CONSTANCE_REDIS_CONNECTION = {
    'host': REDIS_HOST,
    'port': REDIS_PORT,
    'db': 0,
}

CACHES = {
    'default': {
        'BACKEND': 'redis_cache.RedisCache',
        'LOCATION': [
            '{0}:{1}'.format(REDIS_HOST, REDIS_PORT)
        ],
        'OPTIONS': {
            'DB': 1,
        }
    },
    'sessions': {
        'BACKEND': 'redis_cache.RedisCache',
        'LOCATION': [
            '{0}:{1}'.format(REDIS_HOST, REDIS_PORT)
        ],
        'OPTIONS': {
            'DB': 2,
        }
    },
}

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/
STATIC_ROOT = 'static'
STATIC_URL = '/static/'

STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static'),
)
