# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-21 21:06
from __future__ import unicode_literals

from django.db import migrations


items = [
    {
        'title': 'Misión',
        'description':'<p>Contamos con un equipo de trabajo dedicado y de calidad desarrollando la capacitación humana y técnica entregando cada uno de nuestros productos representados en el esfuerzo y la seguridad garantizando las normas técnicas nacionales e internacionales.</p><p><strong>INGELESER</strong> prevé que su crecimiento económico redunde en mejoramiento de procesos, desarrollo del personal y beneficio social.</p>',
        'slug': 'mision',
    },
    {
        'title': 'Visión',
        'description':'<p>En el 2022 seremos una empresa líder en el mercado a nivel nacional en la fabricación y montaje de tableros eléctricos y de control; <strong>INGELESER</strong> será distinguida por ofrecer productos y servicios de calidad contribuyendo con el desarrollo del país cumpliendo con los estándares de calidad.</p>',
        'slug': 'vision',
    },
    {
        'title': 'Politica de Calidad',
        'description':'<p><strong>INGELESER</strong> es una empresa dedicada al servicio profesional de ingeniería electromecánica, mantenimiento, diseño, instalaciones y asesorías a nivel local y regional, desarrolla sus proyectos y actividades asegurando aplicar los más altos estándares de la gestión de la calidad, seguridad y salud en el trabajo en todos sus centros de trabajo con apoyo de todos sus trabajadores, en cada una de sus actividades y sitios de trabajo, buscando la satisfacción de las necesidades y expectativas de sus clientes, por lo cual es nuestro compromiso:</p> <ul><li>Satisfacer las necesidades y expectativas de nuestros clientes.</li><li>Cumplir los requisitos legales aplicables y demás suscritos por la organización con sus partes interesadas y clientes.</li><li>Fortalecer el desarrollo de las competencias de los trabajadores mediante procesos de formación continua.</li><li>Promover la calidad de vida laboral, manteniendo ambientes de trabajo saludables para prevenir la ocurrencia de incidentes, lesiones personales, enfermedades ocupacionales y de origen común, daños a la propiedad a las partes interesadas.</li><li>Identificar y controlar los riesgos para minimizar los efectos ocasionados a los trabajadores, comunidad o la propiedad.</li><li>Mejorar continuamente los estándares del Sistema de Gestión de la Calidad.</li><li>Proporcionar los recursos humanos, técnicos y económicos necesarios para la implementación, mantenimiento y mejora del Sistema de Gestión de la Calidad.</li></ul><p>Es por ello por lo que <strong>INGELESER</strong> desde la gerencia su principal prioridad es hacer cumplimiento del Sistema de Gestión de la Calidad, encaminado siempre a la mejora continua y a la eficacia de nuestro sistema de gestión y de cada uno de sus procesos, así como el compromiso de la alta dirección para el cumplimiento de objetivos y metas definidas.</p>',
        'slug': 'politica-de-calidad',
    },
]


def generate_initial_info(apps, schema_editor):
    CorporativeInfoModel = apps.get_model('corporativeinfo', 'CorporativeInfo')

    for item in items:
        obj = CorporativeInfoModel(**item)
        obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('corporativeinfo', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(generate_initial_info),
    ]
