# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-26 22:07
from __future__ import unicode_literals

import service.app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporativeinfo', '0002_auto_20170921_2106'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='nombre')),
                ('work', models.TextField(blank=True, null=True, verbose_name='descripción')),
                ('logo', models.ImageField(max_length=256, upload_to='', validators=[service.app.validators.FileSizeValidator(4000)], verbose_name='logo')),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=256, upload_to='', validators=[service.app.validators.FileSizeValidator(4000)], verbose_name='imagen')),
            ],
            options={
                'verbose_name': 'ítem de galería',
                'verbose_name_plural': 'ítems de galería',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='nombre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='descripción')),
            ],
            options={
                'verbose_name': 'servicio',
                'verbose_name_plural': 'servicios',
                'ordering': ('id',),
            },
        ),
    ]
