# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-26 22:32
from __future__ import unicode_literals

from django.db import migrations

services = [
    {
        'name': 'Tableros Eléctricos',
    },
    {
        'name': 'Montajes Eléctricos',
    },
    {
        'name': 'Mantenimiento',
    },
    {
        'name': 'Diseño Eléctrico',
    },
    {
        'name': 'Cableado Estructurado',
    },
]


def generate_initial_services(apps, schema_editor):
    ServiceModel = apps.get_model('corporativeinfo', 'Service')

    for service in services:
        obj = ServiceModel(**service)
        obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('corporativeinfo', '0003_customer_galleryitem_service'),
    ]

    operations = [
        migrations.RunPython(generate_initial_services),
    ]
