# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-27 00:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corporativeinfo', '0004_auto_20170926_1732'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='corporativeinfo',
            options={'ordering': ('id',), 'verbose_name': 'Ítem informativo', 'verbose_name_plural': 'Ítems informativos'},
        ),
        migrations.RemoveField(
            model_name='customer',
            name='work',
        ),
    ]
